### ISSUE TITLE
Handling the difference between Vehicle Announcement Message and Vehicle ID Discovery Response

### ISSUE THREAD

**Issue by blackzed** [tobras/wireshark_doip#6]
Hey,
According to the specification, vehicle announcement messages must be sent to UDP_DISCOVERY port but the vehicle id response message must be sent to the client port(UDP_TEST_EQUIPMENT_REQUEST) from which it received the request. 
So, if a doip node responds to port UDP_TEST_EQUIPMENT_REQUEST on a vehicle discovery request, it is not filtered through as of now. 

1. Can you verify the specifiation requirement regarding the destination port to be used in those two cases?
2. Can you confirm this behaviour?

Thanks.

**Comment by tobras** [comment]
The DoIP dissector is associated with port 13400 for TCP and UDP, via Wireshark's _dissector_add_uint()_ function. I.e. any message on TCP or UDP, to or from port 13400 will be dissected as DoIP.

1. Yes, that’s what it says.

2. I have capture files where a node’s UDP response has destination port UDP_TEST_EQUIPMENT_REQUEST and source port UDP_DISCOVERY. And since UDP_DISCOVERY is 13400 these messages are interpreted as DoIP. However, the standard allows the node’s response to be sent from a dynamically assigned UDP port. If this is the case, this message will not automatically be interpreted as DoIP. This since, there is **no way** for Wireshark to know that this is a DoIP message. In such a case, you can manually use the _Decode As…_ functionality to apply the DoIP dissector to all messages from this dynamic port.
